apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "node-exporter.name" . }}
  labels:
{{ include "node-exporter.labels.stakater" . | indent 4 }}
{{ include "node-exporter.labels.chart" . | indent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{ include "node-exporter.labels.selector" . | indent 8 }}
      name: {{ template "node-exporter.name" . }}
    spec:
      serviceAccountName: prometheus-node-exporter
      hostNetwork: {{ .Values.nodeExporter.daemonset.hostNetwork }}
      hostPID: {{ .Values.nodeExporter.daemonset.hostPID }}
      containers:
      - image:  "{{ .Values.nodeExporter.image.name }}:{{ .Values.nodeExporter.image.tag }}"
        args:
        - "--path.procfs={{ .Values.nodeExporter.daemonset.procfs }}"
        - "--path.sysfs={{ .Values.nodeExporter.daemonset.sysfs }}"
        name: {{ template "node-exporter.name" . }}
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
        readinessProbe:
          httpGet:
            path: /
            port: 9100
          initialDelaySeconds: 20            
        livenessProbe:
          httpGet:
            path: /
            port: 9100
          initialDelaySeconds: 30 
        {{- with .Values.nodeExporter.daemonset.resources }}
        resources:
          {{- with .requests }}
          requests:
            {{- with .memory }}
            memory: {{ . }}
            {{- end }}
            {{- with .cpu }}
            cpu: {{ . }}
            {{- end }}
          {{- end }}
          {{- with .limits }}
          limits:
            {{- with .memory }}
            memory: {{ . }}
            {{- end }}
            {{- with .cpu }}
            cpu: {{ . }}
            {{- end }}
          {{- end }}
        {{- end }}
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: {{ .Values.nodeExporter.daemonset.procfs }}
        - name: sys
          readOnly: true
          mountPath: {{ .Values.nodeExporter.daemonset.sysfs }}
      securityContext: {}
      tolerations:
        - effect: {{ .Values.nodeExporter.daemonset.tolerations.effect }}
          operator: {{ .Values.nodeExporter.daemonset.tolerations.operator }}
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
