apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "{{ .Values.nodeExporter.service.expose }}"
    k8s-app: {{ template "node-exporter.name" . }}
{{ include "node-exporter.labels.stakater" . | indent 4 }}
{{ include "node-exporter.labels.chart" . | indent 4 }}
  name: {{ template "node-exporter.name" . }}
{{- if .Values.nodeExporter.service.annotations }}
  annotations:
{{ toYaml .Values.nodeExporter.service.annotations | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9100
    protocol: TCP
  selector:
{{ include "node-exporter.labels.selector" . | indent 4 }}
