nodeExporter:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 0.15.2
  image:
    name: quay.io/prometheus/node-exporter
    tag: v0.15.2
  daemonset:
    procfs: /host/proc
    sysfs: /host/sys
    hostNetwork: "true"
    hostPID: "true"
    resources:
      requests:
        memory: 30Mi
        cpu: 100m
      limits:
        memory: 50Mi
        cpu: 200m
    tolerations:
        effect: NoSchedule
        operator: Exists
  service:
    annotations:
      config.xposer.stakater.com/Domain: stackator.com
      config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-{{.Namespace}}'
      config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Domain}}'
      config.xposer.stakater.com/TLS: "true"
      xposer.stakater.com/annotations: |-
        kubernetes.io/ingress.class: internal-ingress
        ingress.kubernetes.io/force-ssl-redirect: true
        certmanager.k8s.io/cluster-issuer: letsencrypt-production
    expose: "true"
